{% set name = "FRETBursts" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/OpenSMFS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d60cbd154f0265d10c1141464b6594379279c767c0085454eee520c16e254516

build:
  skip: true   # [py<37]
  number: 0
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - python -m pip install --ignore-installed --no-deps .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - pathlib 
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - seaborn
    - ipywidgets
    - pandas
    - numba
    - lmfit
    - phconvert
    - pytables

test:
  imports:
    - fretbursts
    - fretbursts.phtools.phrates
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://opensmfs.github.io/FRETBursts/
  license: GPLv2
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Burst analysis software for single-molecule FRET experiments.'
  description: |
    FRETBursts is a open source software for burst analysis of freely-diffusing
    single-molecule FRET (smFRET) experiments.
  doc_url: http://fretbursts.readthedocs.io/
  dev_url: https://github.com/OpenSMFS/FRETBursts

extra:
  recipe-maintainers:
    - harripd
    - tritemio
