{% set name = "FRETBursts" %}
{% set version = "0.8.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/OpenSMFS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9333db4e8453a7341b3410b89c633606d0283e7f23e46f83e9c753b9c9d48128

build:
  skip: true   # [py<37]
  number: 1
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - python -m pip install --ignore-installed --no-deps .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - pathlib 
    - importlib-metadata
    - {{ pin_compatible('numpy') }}
    - scipy >=1.2
    - seaborn >=0.11.1
    - pandas >=0.23
    - lmfit >=1.0.1
    - phconvert >=0.8
    - pytables >=3.5

test:
  imports:
    - fretbursts
    - fretbursts.phtools.phrates
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://opensmfs.github.io/FRETBursts/
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE.txt
  summary: 'Burst analysis software for single-molecule FRET experiments.'
  description: |
    FRETBursts is a open source software for burst analysis of freely-diffusing
    single-molecule FRET (smFRET) experiments.
  doc_url: http://fretbursts.readthedocs.io/
  dev_url: https://github.com/OpenSMFS/FRETBursts

extra:
  recipe-maintainers:
    - harripd
    - tritemio
