{% set name = "FRETBursts" %}
{% set version = "0.7" %}
{% set sha256 = "d5df10bcfa62efda530e6a9f8866bfd6603c3d4b07e3e2c99f95a9502f5bb494" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/OpenSMFS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win32]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

host:
  - numpy

requirements:
  build:
    - python
    - setuptools
    - future
    - pathlib  # [py27]
    - cython
    - {{ pin_compatible('numpy') }}
    - matplotlib
    - seaborn
    - lmfit
    - phconvert

  run:
    - python
    - future
    - pathlib  # [py27]
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - seaborn
    - ipywidgets
    - pandas
    - numba
    - lmfit
    - phconvert

test:
  imports:
    - fretbursts
    - fretbursts.phtools.phrates

about:
  home: http://opensmfs.github.io/FRETBursts/
  license: GPLv2
  license_file: LICENSE.txt
  summary: 'Burst analysis software for single-molecule FRET experiments.'
  description: |
    FRETBursts is a open source software for burst analysis of freely-diffusing
    single-molecule FRET (smFRET) experiments.
  doc_url: http://fretbursts.readthedocs.io/
  dev_url: https://github.com/tritemio/FRETBursts

extra:
  recipe-maintainers:
    - tritemio
